apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-manifests
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/realestate-trust/monorepo.git'
    targetRevision: HEAD
    path: infra/kind/manifests
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: realestate-trust
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
