apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: realestate-trust-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/NItishSh/realestate-trust.git'
    targetRevision: fix-local-helm-ports
    path: infra/gitops # Path to our service declarations
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: realestate-trust
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
