image:
  repository: ghcr.io/realestate-trust/monorepo/frontend
service:
  type: ClusterIP
  port: 3000
  targetPort: 3000
healthCheck:
  path: /
resources: {}

keda:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "75"
