{{- if .Values.smokeTest.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-smoke-test
  labels:
    app: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-smoke-test
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: smoke-test
        image: curlimages/curl:7.85.0
        command:
        - "sh"
        - "-c"
        - |
          {{- tpl .Values.smokeTest.script . | nindent 10 }}
      restartPolicy: Never
  backoffLimit: 2
{{- end }}
