package db

import (
	"bytes"
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"errors"
	"io"
	"net/http"
	"os"
	"time"
)

// getEncryptionKey retrieves the key from environment, falling back to a default,
// and derives a secure 32-byte key using SHA-256.
func getEncryptionKey() []byte {
	keyStr := os.Getenv("KYC_ENCRYPTION_KEY")
	if keyStr == "" {
		keyStr = "dev-key-must-be-32-bytes-long!!!"
	}
	hash := sha256.Sum256([]byte(keyStr))
	return hash[:]
}

// EncryptKYC encrypts a document reference using Vault Transit engine if configured,
// falling back to local AES-256-GCM.
func EncryptKYC(plaintext string) (string, error) {
	vaultAddr := os.Getenv("VAULT_ADDR")
	vaultToken := os.Getenv("VAULT_TOKEN")

	if vaultAddr != "" && vaultToken != "" {
		ciphertext, err := encryptWithVault(vaultAddr, vaultToken, plaintext)
		if err == nil {
			return ciphertext, nil
		}
		// If Vault fails, we fall back to local GCM to ensure robustness in tests
	}

	return encryptLocal(plaintext)
}

// DecryptKYC base64 decodes and decrypts an encrypted document reference using Vault
// Transit engine if it starts with "vault:", otherwise using local AES-256-GCM.
func DecryptKYC(ciphertext string) (string, error) {
	vaultAddr := os.Getenv("VAULT_ADDR")
	vaultToken := os.Getenv("VAULT_TOKEN")

	// If the ciphertext is generated by Vault, it starts with "vault:"
	if len(ciphertext) > 6 && ciphertext[:6] == "vault:" {
		if vaultAddr != "" && vaultToken != "" {
			plaintext, err := decryptWithVault(vaultAddr, vaultToken, ciphertext)
			if err == nil {
				return plaintext, nil
			}
		}
	}

	return decryptLocal(ciphertext)
}

func encryptWithVault(addr, token, plaintext string) (string, error) {
	url := addr + "/v1/transit/encrypt/kyc-key"
	encodedPlaintext := base64.StdEncoding.EncodeToString([]byte(plaintext))

	reqBody, err := json.Marshal(map[string]string{
		"plaintext": encodedPlaintext,
	})
	if err != nil {
		return "", err
	}

	client := &http.Client{Timeout: 5 * time.Second}
	req, err := http.NewRequest("POST", url, bytes.NewBuffer(reqBody))
	if err != nil {
		return "", err
	}

	req.Header.Set("X-Vault-Token", token)
	req.Header.Set("Content-Type", "application/json")

	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}
	defer func() { _ = resp.Body.Close() }()

	if resp.StatusCode != http.StatusOK {
		return "", errors.New("vault encrypt request failed with status: " + resp.Status)
	}

	var response struct {
		Data struct {
			Ciphertext string `json:"ciphertext"`
		} `json:"data"`
	}

	if err := json.NewDecoder(resp.Body).Decode(&response); err != nil {
		return "", err
	}

	return response.Data.Ciphertext, nil
}

func decryptWithVault(addr, token, ciphertext string) (string, error) {
	url := addr + "/v1/transit/decrypt/kyc-key"

	reqBody, err := json.Marshal(map[string]string{
		"ciphertext": ciphertext,
	})
	if err != nil {
		return "", err
	}

	client := &http.Client{Timeout: 5 * time.Second}
	req, err := http.NewRequest("POST", url, bytes.NewBuffer(reqBody))
	if err != nil {
		return "", err
	}

	req.Header.Set("X-Vault-Token", token)
	req.Header.Set("Content-Type", "application/json")

	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}
	defer func() { _ = resp.Body.Close() }()

	if resp.StatusCode != http.StatusOK {
		return "", errors.New("vault decrypt request failed with status: " + resp.Status)
	}

	var response struct {
		Data struct {
			Plaintext string `json:"plaintext"`
		} `json:"data"`
	}

	if err := json.NewDecoder(resp.Body).Decode(&response); err != nil {
		return "", err
	}

	decodedBytes, err := base64.StdEncoding.DecodeString(response.Data.Plaintext)
	if err != nil {
		return "", err
	}

	return string(decodedBytes), nil
}

func encryptLocal(plaintext string) (string, error) {
	key := getEncryptionKey()
	block, err := aes.NewCipher(key)
	if err != nil {
		return "", err
	}

	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return "", err
	}

	nonce := make([]byte, gcm.NonceSize())
	if _, err := io.ReadFull(rand.Reader, nonce); err != nil {
		return "", err
	}

	ciphertext := gcm.Seal(nonce, nonce, []byte(plaintext), nil)
	return base64.StdEncoding.EncodeToString(ciphertext), nil
}

func decryptLocal(ciphertextBase64 string) (string, error) {
	ciphertext, err := base64.StdEncoding.DecodeString(ciphertextBase64)
	if err != nil {
		return "", err
	}

	key := getEncryptionKey()
	block, err := aes.NewCipher(key)
	if err != nil {
		return "", err
	}

	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return "", err
	}

	nonceSize := gcm.NonceSize()
	if len(ciphertext) < nonceSize {
		return "", errors.New("ciphertext too short")
	}

	nonce, actualCiphertext := ciphertext[:nonceSize], ciphertext[nonceSize:]
	plaintext, err := gcm.Open(nil, nonce, actualCiphertext, nil)
	if err != nil {
		return "", err
	}

	return string(plaintext), nil
}
